CREATE TABLE schema_versions(version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE users(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), username text UNIQUE NOT NULL, password_hash text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE tenants(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), name text NOT NULL);
CREATE TABLE memberships(user_id uuid NOT NULL REFERENCES users(id), tenant_id uuid NOT NULL REFERENCES tenants(id), role text NOT NULL CHECK(role IN ('admin','streamer','operator','viewer')), edit_granted boolean NOT NULL DEFAULT false, PRIMARY KEY(user_id,tenant_id));
CREATE TABLE auth_sessions(token_hash bytea PRIMARY KEY, user_id uuid NOT NULL REFERENCES users(id), tenant_id uuid NOT NULL REFERENCES tenants(id), expires_at timestamptz NOT NULL);
CREATE TABLE inputs(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), name text NOT NULL, orientation text NOT NULL CHECK(orientation IN ('horizontal','vertical','master')), token_hash bytea NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id));
CREATE TABLE destinations(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), name text NOT NULL, platform text NOT NULL, secret jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id));
CREATE TABLE profiles(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), name text NOT NULL, revision integer NOT NULL DEFAULT 1, settings jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id,revision));
CREATE TABLE sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenants(id), name text NOT NULL, state text NOT NULL DEFAULT 'idle' CHECK(state IN ('idle','preparing','waiting','testing','armed','starting','live','degraded','stopping','ended','failed')), mode text NOT NULL DEFAULT 'test' CHECK(mode IN ('test','live')), revision bigint NOT NULL DEFAULT 1, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), UNIQUE(tenant_id,id));
CREATE TABLE outbox(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), resource_id uuid NOT NULL, kind text NOT NULL, payload jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_events(id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, tenant_id uuid NOT NULL REFERENCES tenants(id), actor_id uuid NOT NULL REFERENCES users(id), action text NOT NULL, resource_id text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE idempotency(tenant_id uuid NOT NULL REFERENCES tenants(id), key text NOT NULL, request_hash bytea NOT NULL, response jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(tenant_id,key));
CREATE INDEX outbox_tenant_sequence ON outbox(tenant_id,id);
CREATE INDEX audit_tenant_time ON audit_events(tenant_id,created_at);
CREATE INDEX sessions_tenant ON sessions(tenant_id);
CREATE INDEX auth_session_expiry ON auth_sessions(expires_at);
ALTER TABLE inputs ENABLE ROW LEVEL SECURITY; ALTER TABLE inputs FORCE ROW LEVEL SECURITY;
ALTER TABLE destinations ENABLE ROW LEVEL SECURITY; ALTER TABLE destinations FORCE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY; ALTER TABLE profiles FORCE ROW LEVEL SECURITY;
ALTER TABLE sessions ENABLE ROW LEVEL SECURITY; ALTER TABLE sessions FORCE ROW LEVEL SECURITY;
ALTER TABLE outbox ENABLE ROW LEVEL SECURITY; ALTER TABLE outbox FORCE ROW LEVEL SECURITY;
ALTER TABLE audit_events ENABLE ROW LEVEL SECURITY; ALTER TABLE audit_events FORCE ROW LEVEL SECURITY;
ALTER TABLE idempotency ENABLE ROW LEVEL SECURITY; ALTER TABLE idempotency FORCE ROW LEVEL SECURITY;
CREATE POLICY tenant_isolation ON inputs USING (tenant_id::text = current_setting('app.tenant_id',true)) WITH CHECK (tenant_id::text = current_setting('app.tenant_id',true));
CREATE POLICY tenant_isolation ON destinations USING (tenant_id::text = current_setting('app.tenant_id',true)) WITH CHECK (tenant_id::text = current_setting('app.tenant_id',true));
CREATE POLICY tenant_isolation ON profiles USING (tenant_id::text = current_setting('app.tenant_id',true)) WITH CHECK (tenant_id::text = current_setting('app.tenant_id',true));
CREATE POLICY tenant_isolation ON sessions USING (tenant_id::text = current_setting('app.tenant_id',true)) WITH CHECK (tenant_id::text = current_setting('app.tenant_id',true));
CREATE POLICY tenant_isolation ON outbox USING (tenant_id::text = current_setting('app.tenant_id',true)) WITH CHECK (tenant_id::text = current_setting('app.tenant_id',true));
CREATE POLICY tenant_isolation ON audit_events USING (tenant_id::text = current_setting('app.tenant_id',true)) WITH CHECK (tenant_id::text = current_setting('app.tenant_id',true));
CREATE POLICY tenant_isolation ON idempotency USING (tenant_id::text = current_setting('app.tenant_id',true)) WITH CHECK (tenant_id::text = current_setting('app.tenant_id',true));
GRANT USAGE ON SCHEMA public TO tdr_app;
GRANT SELECT,INSERT,UPDATE,DELETE ON ALL TABLES IN SCHEMA public TO tdr_app;
REVOKE UPDATE,DELETE ON audit_events FROM tdr_app;
REVOKE INSERT,UPDATE,DELETE ON schema_versions FROM tdr_app;
GRANT USAGE,SELECT ON ALL SEQUENCES IN SCHEMA public TO tdr_app;
INSERT INTO schema_versions(version) VALUES(1);
