// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AuditEvent struct {
	ID         int64              `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ActorID    pgtype.UUID        `json:"actor_id"`
	Action     string             `json:"action"`
	ResourceID string             `json:"resource_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type AuthSession struct {
	TokenHash []byte             `json:"token_hash"`
	UserID    pgtype.UUID        `json:"user_id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Destination struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Platform  string             `json:"platform"`
	Secret    []byte             `json:"secret"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Idempotency struct {
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Key         string             `json:"key"`
	RequestHash []byte             `json:"request_hash"`
	Response    []byte             `json:"response"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Input struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	Name        string             `json:"name"`
	Orientation string             `json:"orientation"`
	TokenHash   []byte             `json:"token_hash"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Membership struct {
	UserID      pgtype.UUID `json:"user_id"`
	TenantID    pgtype.UUID `json:"tenant_id"`
	Role        string      `json:"role"`
	EditGranted bool        `json:"edit_granted"`
}

type Outbox struct {
	ID         int64              `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	ResourceID pgtype.UUID        `json:"resource_id"`
	Kind       string             `json:"kind"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Profile struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	Revision  int32              `json:"revision"`
	Settings  []byte             `json:"settings"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type SchemaVersion struct {
	Version   int32              `json:"version"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type Session struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Name      string             `json:"name"`
	State     string             `json:"state"`
	Mode      string             `json:"mode"`
	Revision  int64              `json:"revision"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
