// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions(tenant_id,name) VALUES($1::uuid,$2) RETURNING id::text, tenant_id::text, name, state, mode, revision, created_at, updated_at
`

type CreateSessionParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Name    string      `json:"name"`
}

type CreateSessionRow struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	State     string             `json:"state"`
	Mode      string             `json:"mode"`
	Revision  int64              `json:"revision"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (CreateSessionRow, error) {
	row := q.db.QueryRow(ctx, createSession, arg.Column1, arg.Name)
	var i CreateSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.State,
		&i.Mode,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id::text, tenant_id::text, name, state, mode, revision, created_at, updated_at FROM sessions WHERE tenant_id = $1::uuid AND id = $2::uuid FOR UPDATE
`

type GetSessionParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Column2 pgtype.UUID `json:"column_2"`
}

type GetSessionRow struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	State     string             `json:"state"`
	Mode      string             `json:"mode"`
	Revision  int64              `json:"revision"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetSession(ctx context.Context, arg GetSessionParams) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, arg.Column1, arg.Column2)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.State,
		&i.Mode,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSessions = `-- name: ListSessions :many
SELECT id::text, tenant_id::text, name, state, mode, revision, created_at, updated_at FROM sessions WHERE tenant_id = $1::uuid ORDER BY created_at DESC LIMIT $2 OFFSET $3
`

type ListSessionsParams struct {
	Column1 pgtype.UUID `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

type ListSessionsRow struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	State     string             `json:"state"`
	Mode      string             `json:"mode"`
	Revision  int64              `json:"revision"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsRow{}
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.State,
			&i.Mode,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSession = `-- name: UpdateSession :one
UPDATE sessions SET state=$3, mode=$4, revision=revision+1,updated_at=now() WHERE tenant_id=$1::uuid AND id=$2::uuid AND revision=$5 RETURNING id::text, tenant_id::text, name, state, mode, revision, created_at, updated_at
`

type UpdateSessionParams struct {
	Column1  pgtype.UUID `json:"column_1"`
	Column2  pgtype.UUID `json:"column_2"`
	State    string      `json:"state"`
	Mode     string      `json:"mode"`
	Revision int64       `json:"revision"`
}

type UpdateSessionRow struct {
	ID        string             `json:"id"`
	TenantID  string             `json:"tenant_id"`
	Name      string             `json:"name"`
	State     string             `json:"state"`
	Mode      string             `json:"mode"`
	Revision  int64              `json:"revision"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) (UpdateSessionRow, error) {
	row := q.db.QueryRow(ctx, updateSession,
		arg.Column1,
		arg.Column2,
		arg.State,
		arg.Mode,
		arg.Revision,
	)
	var i UpdateSessionRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.State,
		&i.Mode,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
